package meetingschedulingsystem;

import javax.swing.DefaultListModel;


public class SearchTimeSlotDialog extends javax.swing.JDialog {

    /**
     * Creates new form SearchTimeSlotDialog
     */
    public SearchTimeSlotDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initSettings();
        String values[] = new String[] {
            "9 AM", 
            "10 AM", 
            "11 AM", 
            "12 PM", 
            "1 PM", 
            "2 PM", 
            "3 PM", 
            "4 PM"};
        timeSpinner.setModel(new javax.swing.SpinnerListModel(values));
        timeSpinner.setToolTipText("The meeting time.");
        meetingsList.setModel(new DefaultListModel<>());
    }
    
    /**
     * Initializes the settings
     */
    private void initSettings() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        meetingsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        timeSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM"}));

        jLabel1.setText("Timeslot:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        meetingsList.setToolTipText("List of meetings");
        jScrollPane1.setViewportView(meetingsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(searchButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String spinnerVal = timeSpinner.getValue().toString().substring(0, 2);
        spinnerVal = spinnerVal.trim();
        int spinnerTime = Integer.parseInt(spinnerVal);
        DefaultListModel<String> lm = new DefaultListModel<>();
        for (Meeting meet: DataManager.getMeetings()) {
            if (meet.getTimeSlot() == spinnerTime){
                lm.addElement(meet.fullString());
            }
        }
        meetingsList.setModel(lm);
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> meetingsList;
    private javax.swing.JButton searchButton;
    private javax.swing.JSpinner timeSpinner;
    // End of variables declaration//GEN-END:variables
}
